### ISSUE TITLE
i run mxnet in docker，when i enlarge batch_size have a error ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by qinzhenyi1314** [yeasy/docker_practice#401]
### Environment
* [x] Ubuntu 16.04 +

### Docker Version
Docker version 18.09.1, build 4c52b90

### Problem Description
i run mxnet in docker，when i enlarge batch_size have a error ConnectionResetError: [Errno 104] Connection reset by peer

my machine
| 0 GeForce GTX 980 Ti Off | 00000000:01:00.0 Off | N/A |
| 33% 37C P0 46W / 280W | 0MiB / 6082MiB | 0% Default |

batch_size 128 everyting is ok

batch_size 256 gpu memory Fully enough but The following error occurred

Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/opt/mxnet/python/mxnet/gluon/data/dataloader.py", line 175, in fetcher_loop
idx, batch = data_queue.get()
File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
return ForkingPickler.loads(res)
File "/opt/mxnet/python/mxnet/gluon/data/dataloader.py", line 56, in rebuild_ndarray
fd = fd.detach()
File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
with _resource_sharer.get_connection(self._id) as conn:
File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
c = Client(address, authkey=process.current_process().authkey)
File "/usr/lib/python3.5/multiprocessing/connection.py", line 493, in Client
answer_challenge(c, authkey)
File "/usr/lib/python3.5/multiprocessing/connection.py", line 732, in answer_challenge
message = connection.recv_bytes(256) # reject large message
File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
buf = self._recv_bytes(maxlength)
File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
buf = self._recv(4)
File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by yeasy** [comment]
Maybe you should ask in the mxnet mail-list.
Seems not a docker problem but application issue.
